#!/usr/bin/env python3
"""Generates ui/material/icons/icons.go from google/material-design-icons.

Usage:
  git clone --depth 1 --filter=blob:none --sparse https://github.com/google/material-design-icons mdi
  (cd mdi && git sparse-checkout set --no-cone '/LICENSE' '/src/*/*/materialicons/24px.svg')
  python3 tools/genicons/genicons.py mdi | gofmt > ui/material/icons/icons.go
"""
import glob, os, re, sys
import xml.etree.ElementTree as ET

root = sys.argv[1]
NS = '{http://www.w3.org/2000/svg}'

def fmt(v):
    s = ('%.3f' % float(v)).rstrip('0').rstrip('.')
    return s if s not in ('-0', '') else '0'

def shape_to_d(el):
    tag = el.tag.replace(NS, '')
    a = el.attrib
    if a.get('fill') == 'none' or a.get('opacity') not in (None, '1', '1.0') or a.get('display') == 'none':
        return None
    if tag == 'path':
        return a.get('d')
    if tag == 'circle':
        cx, cy, r = float(a.get('cx', 0)), float(a.get('cy', 0)), float(a['r'])
        return f"M{fmt(cx-r)} {fmt(cy)}a{fmt(r)} {fmt(r)} 0 1 0 {fmt(2*r)} 0a{fmt(r)} {fmt(r)} 0 1 0 {fmt(-2*r)} 0z"
    if tag == 'ellipse':
        cx, cy, rx, ry = float(a.get('cx', 0)), float(a.get('cy', 0)), float(a['rx']), float(a['ry'])
        return f"M{fmt(cx-rx)} {fmt(cy)}a{fmt(rx)} {fmt(ry)} 0 1 0 {fmt(2*rx)} 0a{fmt(rx)} {fmt(ry)} 0 1 0 {fmt(-2*rx)} 0z"
    if tag == 'rect':
        x, y, w, h = float(a.get('x', 0)), float(a.get('y', 0)), float(a['width']), float(a['height'])
        if x == 0 and y == 0 and w == 24 and h == 24:
            return None  # bounding box helper
        rx = float(a.get('rx', a.get('ry', 0)))
        if rx:
            ry = float(a.get('ry', rx))
            return (f"M{fmt(x+rx)} {fmt(y)}h{fmt(w-2*rx)}a{fmt(rx)} {fmt(ry)} 0 0 1 {fmt(rx)} {fmt(ry)}v{fmt(h-2*ry)}"
                    f"a{fmt(rx)} {fmt(ry)} 0 0 1 {fmt(-rx)} {fmt(ry)}h{fmt(-(w-2*rx))}a{fmt(rx)} {fmt(ry)} 0 0 1 {fmt(-rx)} {fmt(-ry)}"
                    f"v{fmt(-(h-2*ry))}a{fmt(rx)} {fmt(ry)} 0 0 1 {fmt(rx)} {fmt(-ry)}z")
        return f"M{fmt(x)} {fmt(y)}h{fmt(w)}v{fmt(h)}h{fmt(-w)}z"
    if tag == 'polygon':
        pts = re.findall(r'-?[\d.]+(?:e-?\d+)?', a['points'])
        pairs = [f"{fmt(pts[i])} {fmt(pts[i+1])}" for i in range(0, len(pts) - 1, 2)]
        return 'M' + 'L'.join(pairs) + 'z'
    return None

def ident(name):
    parts = [p for p in name.split('_') if p]
    s = ''.join(p[:1].upper() + p[1:] for p in parts)
    if s[0].isdigit():
        s = 'N' + s
    return s

icons, skipped = {}, []
for f in sorted(glob.glob(os.path.join(root, 'src/*/*/materialicons/24px.svg'))):
    name = f.split('/')[-3]
    if name in icons:
        continue
    tree = ET.parse(f)
    ds, bad = [], False
    for el in tree.iter():
        if el.attrib.get('transform'):
            bad = True
        d = shape_to_d(el)
        if d and d.strip() not in ('M0 0h24v24H0z', 'M0 0h24v24H0V0z', 'M0,0h24v24H0V0z'):
            ds.append(d.strip())
    if bad or not ds:
        skipped.append(name)
        continue
    icons[name] = ' '.join(ds)

seen, pairs = {}, []
out = ['// Code generated by tools/genicons; DO NOT EDIT.',
       '//',
       '// Material Icons (filled) by Google, Apache License 2.0:',
       '// https://github.com/google/material-design-icons',
       '',
       'package icons',
       '',
       'import "github.com/minelifes/nectar_ui/ui/vector"',
       '',
       'func i(name, d string) *vector.Icon { return vector.NewIcon(name, 24, d) }',
       '',
       'var (']
for name, d in icons.items():
    idn = ident(name)
    if idn in seen:
        idn += '_'
    seen[idn] = 1
    pairs.append((name, idn))
    out.append(f'\t{idn} = i("{name}", "{d}")')
out.append(')')
out.append('')
out.append('// ByName maps the Material icon name (e.g. "arrow_back") to the icon.')
out.append('var ByName = map[string]*vector.Icon{')
for name, idn in pairs:
    out.append(f'\t"{name}": {idn},')
out.append('}')
print('\n'.join(out))
print(f'{len(icons)} icons, skipped {len(skipped)}: {skipped[:20]}', file=sys.stderr)
